### ISSUE TITLE
Best practice #IMGRES - webP usage

### ISSUE THREAD

**Issue by davidbilik** [strvcom/android#1]
Hi, I'm looking at your `best.md` file and I like it a lot. Having this practices written down can make it really easier in onboarding new people or while doing a code review. One thing that caught my eye is #IMGRES practice - have you considered using webP format of raster images rather than jpg or png? We are using it for couple of years now and the file size and quality is better than those two. The only disadvantage that I know currently is that Gitlab which we use for git management cannot display this images in diffing which can lead to some errors in code review, but it never happened to us yet.

Thanks :)

**Comment by petrnohejl** [comment]
Hi David. Thank you for the comment. You have a great point. We'll take it into account and update #IMGRES.
